### ISSUE TITLE
NemID is closed and causes an error in the authentication flow

### ISSUE THREAD

**Issue by x2q** [dk/Net-Eboks#7]
I'm getting below when going through the authentication flow on [http://localhost:9999/](http://localhost:9999/):

<img width="1155" alt="Screenshot 2024-04-26 at 15 25 21" src="https://github.com/dk/Net-Eboks/assets/245963/f4d68ec7-13d5-4ebd-8750-2cd1597bffb5">

**Comment by dk** [comment]
Hi, I'm hacking around this and the code is very alpha, so if you're interested you can try to test if thew new mitid authentication works for you. Here's the script that also listens on localhost:9999 that tries to upload the public
key to the eboks server. Try to see if it works for you - if yes, then you shall be able to use eboks-dump and eboks2pop out of the box.

The only serious caveat is that it doesn't work in a modern browser because of CORS - one needs to use Chrome with disabled security. Here's more about why and how:  https://github.com/dk/Net-MitDK/blob/master/README.md (Browser security) . 

https://gist.github.com/dk/e8adea143695d3fd71fdc4ef752b94a2
